//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Consumers struct {
	ID          uuid.UUID `sql:"primary_key"`
	Nik         string
	FullName    string
	LegalName   string
	BirthPlace  string
	BirthDate   time.Time
	Salary      int64
	KtpPhoto    string
	SelfiePhoto string
}
