//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Limits struct {
	ConsumerID uuid.UUID `sql:"primary_key"`
	Tenor1     int64
	Tenor2     int64
	Tenor3     int64
	Tenor4     int64
}
