//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Loans struct {
	ID                uuid.UUID `sql:"primary_key"`
	ConsumerID        uuid.UUID
	Amount            int64
	Tenor             int16
	InstallmentLength int16
	ConsumerLimit     int64
	ConsumerSalary    int64
	LoanedAt          *time.Time
	Status            int16
}
