//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type TransactionRecords struct {
	ID          uuid.UUID `sql:"primary_key"`
	ContractID  *string
	LoanID      uuid.UUID
	Otr         *int64
	AdminFee    *int64
	Installment *int64
	Interest    *int64
	AssetName   string
	Amount      int64
	Status      int16
	CatalogID   uuid.UUID
}
